version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=earny_commerce
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=earny
      - DATABASE_HOST=127.0.0.1
    ports:
      - 5432:5432
    volumes:
      - ./project/app/postgres_data:/var/lib/postgres/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=earny
    ports:
      - 5050:80

  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:earny@postgres:5432/earny_commerce
    depends_on:
      - postgres

  prod_web:
    build: ./project
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8005:8080
    environment:
      - DATABASE_URL=<url>